name: Bulk replace HTML links

on:
  workflow_dispatch:  # 在 Actions 页手动触发

permissions:
  contents: write        # 允许提交代码
  pull-requests: write   # 允许创建 PR

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # 拉取代码到工作目录，供后续步骤修改
        # 文档: https://github.com/actions/checkout
      - name: Replace in *.html
        id: replace_html
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "https://vnwb8wxvjr4inj.the.bi/char/ft/"
          replace: "https://mississippi.river.to/right/f/"
          include: "**/*.html"
          exclude: ".git/**, .github/workflows/**"
          regex: "false"   # 关闭正则，做精确字符串替换
      - name: Replace in *.htm
        id: replace_htm
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "https://vnwb8wxvjr4inj.the.bi/char/ft/"
          replace: "https://mississippi.river.to/right/f/"
          include: "**/*.htm"
          exclude: ".git/**, .github/workflows/**"
          regex: "false"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: replace old link prefix in HTML files"
          title: "chore: bulk replace link prefix in HTML files"
          body: |
            Automated replacement:
            - from: https://vnwb8wxvjr4inj.the.bi/char/ft/
            - to:   https://mississippi.river.to/right/f/
            Scope: *.html, *.htm
          branch: "chore/bulk-replace-html-links"
